### ISSUE TITLE
get customer endpoint

### ISSUE THREAD

**Issue by Nifacy** [Nifacy/marketeplace-app#18]
Реализовать endpoint `/customer/{id}`, который ищет покупателя по указанному id

> **Note**
> Для подробностей смотри схему api

**Comment by aRussianSweetie** [comment]
Нужно ли добавлять здесь depency на получение current_user? Типо же любой может просмотреть customer-а по id, нет?

**Comment by Nifacy** [comment]
> Нужно ли добавлять здесь depency на получение current_user? Типо же любой может просмотреть customer-а по id, нет?

Смотри, при описании API я планировал, что получить информацию о customer может любой **авторизованный** пользователь.

То есть, если смотреть на схему - да, надо. Если смотреть на текущую ситуацию - будет вполне больно. В общем, на твое усмотрение 🤓🥰
