### ISSUE TITLE
usecases for order

### ISSUE THREAD

**Issue by Nifacy** [Nifacy/marketeplace-app#5]
Реализовать usecases для заказов, позволяющие создать, просмотреть и изменить заказ. Пока что представляю это как набор следующих методов:

- `create_order`
  **Входные данные:** принимает на вход информацию о заказе (check: схема API)
  **Выходные данные:** *созданный* объект заказа

- `get_order`
  **Входные данные:** принимает на вход параметры фильтрации. Пока что точно могу сказать, что понадобятся id заказа, id продавца, кому принадлежит заказанный товар и id покупателя, сделавшего заказ
  **Выходные данные:** возвращает список *существующих* объектов заказа. Если же заказов не было найдено - возвращает пустой список.

- `update_order_status`
  **Входные данные:** принимает на вход id заказа и обновленный статус заказа
  **Выходные данные:** возвращает обновленный объект заказа.
  Если заказа по указанному id не существует, то надо как-то обработать этот случай.

> P. S. Доменное поведение (кто может изменять статус, на какой статус) предлагается сначала реализовать на уровне Python обертки, а потом, если получится, перенести в SQL функцию.

**Comment by aRussianSweetie** [comment]
А ещё у меня гигантский проеб
Я всё написал во множественном числе. Так что ксож не по формату. Но я точно сломаю всё, если щас полезу все переименовывать. Похуй.

**Comment by Nifacy** [comment]
> Насчет того, чтобы сделать так, чтобы только customer мог создавать заказы. Эта шняга должна быть на уровне endpointов.

если ты про тесты, то очевидно да. На уровне usecase-ов все эти функции выполняются "безличностно" - то есть, нам не важно, от лица кого они вызываются.
